name: actiniumbravohoneydew
version: '0.1.0.0'
author: Chris Stryczynski
maintainer: Chris Stryczynski
license: MIT
dependencies:
- base >=4.12 && <4.13
- string-conversions
library:
  source-dirs: src
